

services:
  app:
    build: .
    container_name: meu-app-devops
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/loja
    depends_on:
      - db
    # Note: Removemos o "ports" daqui, pois agora só o Nginx fala com o app

  db:
    image: postgres:15
    container_name: meu-banco-dados
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=loja
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: meu-servidor-web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data: